# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

['http://www.24-7.co.jp/',
'http://www.turbine.co.jp/profile/outline',
'http://www.mother.co.jp/',
'http://webright.co.jp/',
'http://www.ab-net.co.jp/',
'http://www.coosy.co.jp/',
'http://webkikaku.co.jp/',
'http://www.sinkyone.com/aboutus/company/',
'http://www.eway.jp/',
'http://www.tamonten.co.jp/',
'http://www.patweb.jp/',
'http://www.mdm-web.jp/',
'http://www.lampros.co.jp/',
'http://www.freemind.co.jp/',
'http://baqemono.jp/',
'http://www.sole-color.co.jp/',
'http://www.e-bird.biz/recruit/',
'http://www.kurabiz.jp/',
'http://www.advance.ws/contents/web/web.html',
'http://www.comotec.ne.jp/',
'http://www.tam-tam.co.jp/',
'http://weva.jp/',
'http://www.sangonana.jp/',
'http://www.infosmile.co.jp/',
'http://www.ryukyu-i.co.jp/',
'http://www.alleyoop.co.jp/',
'http://web.j-line.co.jp/',
'http://www.alpha-create.ne.jp/',
'http://www.n-e-u.co.jp/company/',
'http://leapy.jp/',
'http://liginc.co.jp/web',
'http://liginc.co.jp/web/tool/157624',
'https://www.netforest.ad.jp/',
'http://seek.vc/',
'http://www.dimsite.jp/',
'https://www.gpol.co.jp/',
'http://www.web-works.ne.jp/',
'http://www.weska.jp/',
'http://www.tifana.com/',
'http://www.root-sea.co.jp/',
'https://www.eyemovic.com/',
'http://web-trickster.com/',
'http://163.a-jflat.com/',
'https://www.fvs-net.co.jp/',
'http://www.hu-connect.co.jp/',
'http://www.ccc-inc.com/',
'http://aura-office.co.jp/',
'http://www.deep-deep.jp/',
'http://www.frontier-web.co.jp/',
'http://www.dg-index.jp/',
'http://www.kikakuseisaku.com/',
'http://www.i-order.co.jp/',
'http://www.gooya.co.jp/',
'http://www.creation-file.jp/',
'http://www.netoption.co.jp/',
'http://web-trust.co.jp/',
'http://www.exe-creation.com/',
'http://web3.co.jp/',
'http://www.goowa.jp/',
'http://www.liveknott.co.jp/',
'http://prismgate.jp/',
'http://www.plusline.jp/',
'http://www.ibnet.ne.jp/',
'http://www.web-current.co.jp/',
'http://www.stagegroup.jp/company/',
'http://www.sneaz.co.jp/',
'http://www.flavours.ac/',
'http://d-w.jp/',
'http://www.prart.co.jp/',
'http://www.ingsnet.co.jp/',
'https://www.bitforest.jp/',
'https://www.cis-trans.jp/',
'https://www.bitforest.jp/',
'https://www.cis-trans.jp/',
'https://www.bitforest.jp/',
'https://www.cis-trans.jp/',
'http://www.arttech.co.jp/',
'http://www.neos-design.co.jp/',
'http://www.currentex.jp/',
'http://www.sasukedesign.co.jp/',
'http://appeal-ad.co.jp/',
'https://www.nileriver.co.jp/',
'http://www.link-jpn.jp/',
'http://i-deal.jp.net/',
'http://condense-c.com/',
'http://smile-farm.co.jp/',
'http://www.4696.co.jp/',
'http://www.webmax.co.jp/',
'http://www.media-square.co.jp/',
'http://www.code54.net/',
'http://www.talk-to.co.jp/',
'http://infomediary.jp/',
'http://www.blades.co.jp/',
'http://www.inclover-inc.com/',
'http://www.caribou.co.jp/',
'http://www.mirugate.co.jp/',
'http://www.artflair.co.jp/',
'http://www.meme.ne.jp/',
'http://www.jena.ne.jp/',
'http://www.w-star.com/'].each do |url|
    web_page = WebPage.new(:url => url)
    begin
        web_page.save
    rescue => err
        p err.message
    ensure
        puts url
    end
end
